name: Test

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      # You can use PyPy versions in python-version.
      # For example, pypy2 and pypy3
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    #- name: Install dependencies
    #  run: |
    #    python -m pip install --upgrade pip
    #    pip install -r requirements.txt
    - name: Test with unittest
      run: |
        python -m unittest discover -s tests -p 'test_*.py'
